# Generated by Django 4.2.7 on 2023-12-07 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0006_alter_bb_options_alter_bb_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='bb',
            order_with_respect_to=None,
        ),
    ]
